assetDir = "static"
baseURL = "/"
disableAliases = true
enableRobotsTXT = true
googleAnalytics = "UA-122587276-1"
languageCode = "en-gb"
title = "Lake Martin Mini Mall"
[imaging]
anchor = "center"
quality = 90

[[menu.main]]
name = "Furniture"
url = "/furniture/"
weight = 4
[[menu.main]]
name = "Big Green Egg"
url = "/big-green-egg/"
weight = 2
[[menu.main]]
name = "Decor"
url = "/decor/"
weight = 6
[[menu.main]]
name = "Outdoor"
url = "/outdoor"
weight = 3
[[menu.main]]
name = "Gifts & Apparel"
url = "/gifts-apparel"
weight = 5
[[menu.main]]
name = "Visit Us"
url = "/visit-us/"
weight = 1

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true


[params]
description = "Family owned and operated by Jason & Scott Lett as of 2013, Lake Martin Mini Mall is conveniently located on Hwy 63, just north of Eclectic, AL.  We serve the Lake Martin area, but can ship anywhere in the U.S.  With over an acre of water fountains, statuary, planters, and more, we are able to offer a wide selection of concrete pottery."
facebook = ""
instagram = ""
pinterest = ""
