baseURL = "/"
disableAliases = true
enableRobotsTXT = true
languageCode = "en-gb"
title = "Lake Martin Mini Mall"
[mediaTypes."text/netlify"]
delimiter = ""
suffix = ""
[[menu.main]]
name = "Statuary & Pottery"
url = "/statuary-pottery"
weight = 2
[[menu.main]]
name = "Furniture"
url = "/furniture/"
weight = 3
[[menu.main]]
name = "Big Green Egg"
url = "/big-green-egg/"
weight = 2
[[menu.main]]
name = "Visit Us"
url = "/visit-us/"
weight = 1
[[menu.main]]
name = "Decor"
url = "/decor/"
weight = 5
[[menu.main]]
name = "Outdoor"
url = "/outdoor/"
weight = 4
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
[params]
description = "Family owned and operated by Jason & Scott Lett as of 2013, Lake Martin Mini Mall is conveniently located on Hwy 63, just north of Eclectic, AL.  We serve the Lake Martin area, but can ship anywhere in the U.S.  With over an acre of water fountains, statuary, planters, and more, we are able to offer a wide selection of concrete pottery."
facebook = ""
instagram = ""
pinterest = ""
